from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

EXAMPLE_CONFIG = Path(__file__).parent.parent / "example" / "app_store_suite.example.yaml"

L10N_YAML = """\
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
"""

TEMPLATE_ARB = """\
{{
    "@@locale": "en",
    "appTitle": "{app_name}",
    "@appTitle": {{
        "description": "The title of the application"
    }}
}}
"""

ENV_EXAMPLE = """\
# Copy to .env (gitignored) and fill in real values.

# Required by `appstoresuite translate-arb`.
ARB_TRANSLATE_API_KEY=
"""

FASTFILE = """\
# Generated by `appstoresuite init` as a starting point — `fastlane init` (run
# separately, per-platform) is the better way to wire up real Apple/Google
# credentials. Fill in the build/upload steps for your app; lane names below
# match appstoresuite's defaults (ship-ios -> ship_testflight, ship-android ->
# ship_internal), so `appstoresuite ship-ios` / `ship-android` work as-is once
# these lanes actually build and upload something.

platform :ios do
  lane :ship_testflight do
    # build_app(scheme: "Runner")
    # upload_to_testflight
  end
end

platform :android do
  lane :ship_internal do
    # gradle(task: "bundle", build_type: "Release")
    # upload_to_play_store(track: "internal")
  end
end
"""

APPFILE = """\
# app_identifier("com.yourcompany.yourapp") # iOS bundle id / Android package name
# apple_id("you@example.com") # your Apple ID, used for TestFlight uploads
# json_key_file("keys/your-service-account.json") # Play Console service account
# package_name("com.yourcompany.yourapp") # Android package name, if it differs
"""


@dataclass
class ScaffoldResult:
    created: list[Path]
    skipped: list[Path]


def scaffold_project(
    project_dir: Path,
    config_path: Path | None = None,
    app_name: str | None = None,
    force: bool = False,
) -> ScaffoldResult:
    """Lays down starter files for a new app: app_store_suite.yaml, l10n.yaml
    (+ a template ARB file), .env.example, and a fastlane skeleton.

    Never overwrites an existing file unless force=True.
    """
    created: list[Path] = []
    skipped: list[Path] = []

    def _write(path: Path, content: str) -> None:
        if path.exists() and not force:
            skipped.append(path)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        created.append(path)

    config_path = config_path or (project_dir / "app_store_suite.yaml")
    example = EXAMPLE_CONFIG.read_text()
    if app_name:
        example = example.replace("name: YourApp", f"name: {app_name}")
    _write(config_path, example)

    _write(project_dir / "l10n.yaml", L10N_YAML)
    _write(project_dir / "lib" / "l10n" / "app_en.arb", TEMPLATE_ARB.format(app_name=app_name or "YourApp"))
    _write(project_dir / ".env.example", ENV_EXAMPLE)
    _write(project_dir / "fastlane" / "Fastfile", FASTFILE)
    _write(project_dir / "fastlane" / "Appfile", APPFILE)

    return ScaffoldResult(created=created, skipped=skipped)
