from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

EXAMPLE_CONFIG = Path(__file__).parent.parent / "example" / "app_store_suite.example.yaml"


def _detect_app_name(project_dir: Path) -> str | None:
    """Flutter package name from pubspec.yaml, e.g. `my_app` -> `My App`."""
    pubspec = project_dir / "pubspec.yaml"
    if not pubspec.exists():
        return None
    match = re.search(r"^name:\s*(\S+)", pubspec.read_text(), re.MULTILINE)
    if not match:
        return None
    return match.group(1).replace("_", " ").replace("-", " ").title()


def _detect_bundle_id(project_dir: Path) -> str | None:
    """iOS bundle id from the Runner target's PRODUCT_BUNDLE_IDENTIFIER, skipping
    the RunnerTests target."""
    pbxproj = project_dir / "ios" / "Runner.xcodeproj" / "project.pbxproj"
    if not pbxproj.exists():
        return None
    for match in re.finditer(r"PRODUCT_BUNDLE_IDENTIFIER\s*=\s*([\w.]+);", pbxproj.read_text()):
        value = match.group(1)
        if not value.endswith(".RunnerTests"):
            return value
    return None


def _detect_android_package(project_dir: Path) -> str | None:
    """Android applicationId from android/app/build.gradle(.kts)."""
    for name in ("build.gradle.kts", "build.gradle"):
        gradle = project_dir / "android" / "app" / name
        if not gradle.exists():
            continue
        match = re.search(r'applicationId\s*[= ]\s*"([\w.]+)"', gradle.read_text())
        if match:
            return match.group(1)
    return None

L10N_YAML = """\
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
"""

TEMPLATE_ARB = """\
{{
    "@@locale": "en",
    "appTitle": "{app_name}",
    "@appTitle": {{
        "description": "The title of the application"
    }}
}}
"""

ENV_EXAMPLE = """\
# Copy to .env (gitignored) and fill in real values.

# Required by `appstoresuite translate-arb`.
ARB_TRANSLATE_API_KEY=
"""

FASTFILE = """\
# Generated by `appstoresuite init` as a starting point — `fastlane init` (run
# separately, per-platform) is the better way to wire up real Apple/Google
# credentials. Fill in the build/upload steps for your app; lane names below
# match appstoresuite's defaults (ship-ios -> ship_testflight, ship-android ->
# ship_internal), so `appstoresuite ship-ios` / `ship-android` work as-is once
# these lanes actually build and upload something.

platform :ios do
  lane :ship_testflight do
    # build_app(scheme: "Runner")
    # upload_to_testflight
  end
end

platform :android do
  lane :ship_internal do
    # gradle(task: "bundle", build_type: "Release")
    # upload_to_play_store(track: "internal")
  end
end
"""

APPFILE = """\
{app_identifier_line} # iOS bundle id, detected from ios/Runner.xcodeproj if present
# apple_id("you@example.com") # your Apple ID, used for TestFlight uploads
# json_key_file("keys/your-service-account.json") # Play Console service account
{package_name_line} # Android package name, detected from android/app/build.gradle if present
"""


@dataclass
class ScaffoldResult:
    created: list[Path]
    skipped: list[Path]


def scaffold_project(
    project_dir: Path,
    config_path: Path | None = None,
    app_name: str | None = None,
    force: bool = False,
) -> ScaffoldResult:
    """Lays down starter files for a new app: app_store_suite.yaml, l10n.yaml
    (+ a template ARB file), .env.example, and a fastlane skeleton.

    Never overwrites an existing file unless force=True.
    """
    created: list[Path] = []
    skipped: list[Path] = []

    def _write(path: Path, content: str) -> None:
        if path.exists() and not force:
            skipped.append(path)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        created.append(path)

    app_name = app_name or _detect_app_name(project_dir)
    bundle_id = _detect_bundle_id(project_dir)
    android_package = _detect_android_package(project_dir)

    config_path = config_path or (project_dir / "app_store_suite.yaml")
    example = EXAMPLE_CONFIG.read_text()
    if app_name:
        example = example.replace("name: YourApp", f"name: {app_name}")
    if bundle_id:
        example = example.replace(
            "# bundle_id: com.yourcompany.yourapp", f"bundle_id: {bundle_id}"
        )
    if android_package:
        example = example.replace(
            "# android_package_name: com.yourcompany.yourapp", f"android_package_name: {android_package}"
        )
    _write(config_path, example)

    _write(project_dir / "l10n.yaml", L10N_YAML)
    _write(project_dir / "lib" / "l10n" / "app_en.arb", TEMPLATE_ARB.format(app_name=app_name or "YourApp"))
    _write(project_dir / ".env.example", ENV_EXAMPLE)
    _write(project_dir / "fastlane" / "Fastfile", FASTFILE)

    appfile = APPFILE.format(
        app_identifier_line=(
            f'app_identifier("{bundle_id}")' if bundle_id else '# app_identifier("com.yourcompany.yourapp")'
        ),
        package_name_line=(
            f'package_name("{android_package}")' if android_package else '# package_name("com.yourcompany.yourapp")'
        ),
    )
    _write(project_dir / "fastlane" / "Appfile", appfile)

    return ScaffoldResult(created=created, skipped=skipped)
