from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

EXAMPLE_CONFIG = Path(__file__).parent.parent / "example" / "app_store_suite.example.yaml"


def _detect_app_name(project_dir: Path) -> str | None:
    """Flutter package name from pubspec.yaml, e.g. `my_app` -> `My App`."""
    pubspec = project_dir / "pubspec.yaml"
    if not pubspec.exists():
        return None
    match = re.search(r"^name:\s*(\S+)", pubspec.read_text(), re.MULTILINE)
    if not match:
        return None
    return match.group(1).replace("_", " ").replace("-", " ").title()


def _detect_bundle_id(project_dir: Path) -> str | None:
    """iOS bundle id from the Runner target's PRODUCT_BUNDLE_IDENTIFIER, skipping
    the RunnerTests target."""
    pbxproj = project_dir / "ios" / "Runner.xcodeproj" / "project.pbxproj"
    if not pbxproj.exists():
        return None
    for match in re.finditer(r"PRODUCT_BUNDLE_IDENTIFIER\s*=\s*([\w.]+);", pbxproj.read_text()):
        value = match.group(1)
        if not value.endswith(".RunnerTests"):
            return value
    return None


def _detect_android_package(project_dir: Path) -> str | None:
    """Android applicationId from android/app/build.gradle(.kts)."""
    for name in ("build.gradle.kts", "build.gradle"):
        gradle = project_dir / "android" / "app" / name
        if not gradle.exists():
            continue
        match = re.search(r'applicationId\s*[= ]\s*"([\w.]+)"', gradle.read_text())
        if match:
            return match.group(1)
    return None

L10N_YAML = """\
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
"""

TEMPLATE_ARB = """\
{{
    "@@locale": "en",
    "appTitle": "{app_name}",
    "@appTitle": {{
        "description": "The title of the application"
    }}
}}
"""

ENV_EXAMPLE = """\
# Copy to .env (gitignored) and fill in real values.

# Required by `appstoresuite translate-arb`.
ARB_TRANSLATE_API_KEY=
"""

FASTFILE = """\
# Generated by `appstoresuite init`. Everything here works as-is except the
# four constants below — fill those in with your own credentials and this
# file needs no further changes. Lane names match appstoresuite's defaults
# (ship-ios -> ship_testflight, ship-android -> ship_internal), so
# `appstoresuite ship-ios` / `ship-android` work once the constants are set.

default_platform(:android)

ANDROID_PACKAGE_NAME = "{android_package}"
IOS_BUNDLE_ID = "{bundle_id}"

REPO_ROOT = File.expand_path("..", __dir__)

# Play Console service account JSON (Setup > API access in Play Console).
PLAY_JSON_KEY = File.join(REPO_ROOT, "keys", "your-service-account.json")

# App Store Connect API key (Users and Access > Integrations in App Store Connect).
ASC_KEY_ID = "TODO_ASC_KEY_ID"
ASC_ISSUER_ID = "TODO_ASC_ISSUER_ID"
ASC_KEY_PATH = File.join(REPO_ROOT, "keys", "AuthKey_TODO_ASC_KEY_ID.p8")

def pubspec_version
  content = File.read(File.join(REPO_ROOT, "pubspec.yaml"))
  match = content.match(/^version:\\s*['"]?(\\d+\\.\\d+\\.\\d+)\\+(\\d+)['"]?/)
  UI.user_error!("Could not parse version from pubspec.yaml") unless match
  {{ name: match[1], code: match[2].to_i }}
end

platform :android do
  desc "Check pubspec build number against the highest live Play Store version code, build the AAB, then upload it to internal testing"
  lane :ship_internal do
    v = pubspec_version
    UI.message("Local pubspec version: #{{v[:name]}}+#{{v[:code]}}")

    live_codes = google_play_track_version_codes(
      package_name: ANDROID_PACKAGE_NAME,
      json_key: PLAY_JSON_KEY,
      track: "internal"
    )
    prod_codes = google_play_track_version_codes(
      package_name: ANDROID_PACKAGE_NAME,
      json_key: PLAY_JSON_KEY,
      track: "production"
    )
    highest_live = (live_codes + prod_codes + [0]).max
    UI.message("Highest live Play Store version code: #{{highest_live}}")

    if v[:code] <= highest_live
      UI.user_error!("pubspec.yaml build number (#{{v[:code]}}) must be greater than the highest live Play Store version code (#{{highest_live}}). Bump the +build number in pubspec.yaml and rebuild.")
    end

    UI.message("Building Android App Bundle")
    sh("bash -lc 'cd #{{REPO_ROOT}} && flutter build appbundle'")

    aab_glob = File.join(REPO_ROOT, "build", "app", "outputs", "bundle", "**", "*.aab")
    candidates = Dir.glob(aab_glob)
    UI.user_error!("No .aab found under build/app/outputs/bundle - `flutter build appbundle` did not produce one.") if candidates.empty?
    aab_path = candidates.max_by {{ |f| File.mtime(f) }}
    UI.message("Uploading AAB: #{{aab_path}}")

    supply(
      json_key: PLAY_JSON_KEY,
      package_name: ANDROID_PACKAGE_NAME,
      aab: aab_path,
      track: "internal",
      release_status: "completed",
      skip_upload_changelogs: true,
      skip_upload_metadata: true,
      changes_not_sent_for_review: true
    )
    UI.success("Uploaded #{{v[:name]}}+#{{v[:code]}} to Play Store internal testing")
  end
end

platform :ios do
  desc "Check pubspec build number against the highest live App Store Connect build number, build the ipa, then upload it to TestFlight"
  lane :ship_testflight do
    v = pubspec_version
    UI.message("Local pubspec version: #{{v[:name]}}+#{{v[:code]}}")

    api_key = app_store_connect_api_key(
      key_id: ASC_KEY_ID,
      issuer_id: ASC_ISSUER_ID,
      key_filepath: ASC_KEY_PATH,
      in_house: false
    )

    latest_testflight = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: IOS_BUNDLE_ID
    ).to_i

    latest_live = begin
      app_store_build_number(
        api_key: api_key,
        app_identifier: IOS_BUNDLE_ID,
        live: true
      ).to_i
    rescue StandardError
      0
    end

    highest_live = [latest_testflight, latest_live].max
    UI.message("Highest live App Store Connect build number: #{{highest_live}}")

    if v[:code] <= highest_live
      UI.user_error!("pubspec.yaml build number (#{{v[:code]}}) must be greater than the highest live App Store Connect build number (#{{highest_live}}). Bump the +build number in pubspec.yaml and rebuild.")
    end

    UI.message("Building iOS ipa")
    sh("bash -lc 'cd #{{REPO_ROOT}} && flutter build ipa'")

    ipa_glob = File.join(REPO_ROOT, "build", "ios", "ipa", "*.ipa")
    candidates = Dir.glob(ipa_glob)
    UI.user_error!("No .ipa found under build/ios/ipa - `flutter build ipa` did not produce one.") if candidates.empty?
    ipa_path = candidates.max_by {{ |f| File.mtime(f) }}
    UI.message("Uploading ipa: #{{ipa_path}}")

    upload_to_testflight(
      api_key: api_key,
      ipa: ipa_path,
      app_identifier: IOS_BUNDLE_ID,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
    UI.success("Uploaded #{{v[:name]}}+#{{v[:code]}} to App Store Connect / TestFlight")
  end
end
"""

APPFILE = """\
{app_identifier_line} # iOS bundle id, detected from ios/Runner.xcodeproj if present
# apple_id("you@example.com") # your Apple ID, used for TestFlight uploads
# json_key_file("keys/your-service-account.json") # Play Console service account
{package_name_line} # Android package name, detected from android/app/build.gradle if present
"""

GEMFILE = """\
source "https://rubygems.org"

gem "fastlane"
"""


@dataclass
class ScaffoldResult:
    created: list[Path]
    skipped: list[Path]


def scaffold_project(
    project_dir: Path,
    config_path: Path | None = None,
    app_name: str | None = None,
    force: bool = False,
) -> ScaffoldResult:
    """Lays down starter files for a new app: app_store_suite.yaml, l10n.yaml
    (+ a template ARB file), .env.example, and a fastlane skeleton.

    Never overwrites an existing file unless force=True.
    """
    created: list[Path] = []
    skipped: list[Path] = []

    def _write(path: Path, content: str) -> None:
        if path.exists() and not force:
            skipped.append(path)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        created.append(path)

    app_name = app_name or _detect_app_name(project_dir)
    bundle_id = _detect_bundle_id(project_dir)
    android_package = _detect_android_package(project_dir)

    config_path = config_path or (project_dir / "app_store_suite.yaml")
    example = EXAMPLE_CONFIG.read_text()
    if app_name:
        example = example.replace("name: YourApp", f"name: {app_name}")
    if bundle_id:
        example = example.replace(
            "# bundle_id: com.yourcompany.yourapp", f"bundle_id: {bundle_id}"
        )
    if android_package:
        example = example.replace(
            "# android_package_name: com.yourcompany.yourapp", f"android_package_name: {android_package}"
        )
    _write(config_path, example)

    _write(project_dir / "l10n.yaml", L10N_YAML)
    _write(project_dir / "lib" / "l10n" / "app_en.arb", TEMPLATE_ARB.format(app_name=app_name or "YourApp"))
    _write(project_dir / ".env.example", ENV_EXAMPLE)
    fastfile = FASTFILE.format(
        android_package=android_package or "com.yourcompany.yourapp",
        bundle_id=bundle_id or "com.yourcompany.yourapp",
    )
    _write(project_dir / "fastlane" / "Fastfile", fastfile)

    appfile = APPFILE.format(
        app_identifier_line=(
            f'app_identifier("{bundle_id}")' if bundle_id else '# app_identifier("com.yourcompany.yourapp")'
        ),
        package_name_line=(
            f'package_name("{android_package}")' if android_package else '# package_name("com.yourcompany.yourapp")'
        ),
    )
    _write(project_dir / "fastlane" / "Appfile", appfile)

    _write(project_dir / "Gemfile", GEMFILE)

    return ScaffoldResult(created=created, skipped=skipped)
